security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
    diamante_embedded_form:
      pattern:                        ^/embedded-form/submit-ticket
      provider:                       chain_provider
      anonymous:                      true
    front_diamante:
      pattern:        ^/portal
      provider:       chain_provider
      anonymous:      true
    front_diamante_reset_password:
      pattern:        ^/portal/password/*
      provider:       chain_provider
      anonymous:      true
